### ISSUE TITLE
Implicit visibility level of `mapping(address => uint) index`

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/ADOMedianizer#10]
https://github.com/tellor-io/ADOMedianizer/blob/77e38e08d6941e09c2247573e98711da6f986355/contracts/ADOMedianizer.sol#L9

As per the Solidity documentation:
> The default visibility level in contracts is `public`, in interfaces it is `external`, and state variable default visibility level is `internal`.

The visibility level of `mapping(address => uint) index` is therefore `public`. However, it is not explicitly stated.

This could mistakenly lead developers that are not familiar with the visibility rules above to believe that this data structure is private.

Please explicitly declare the visibility level to avoid ambiguity.

**Comment by brendaloya** [comment]
done
