### ISSUE TITLE
Local variable in `removeOracle` uses argument prefix

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/ADOMedianizer#2]
https://github.com/tellor-io/ADOMedianizer/blob/77e38e08d6941e09c2247573e98711da6f986355/contracts/ADOMedianizer.sol#L48

It is customary in Solidity to use the underscore character (`_`) to prefix arguments of methods. Conversely, they should never be used in variables that are local to the scope of a method.

It is therefore recommended that the `_index` variable in `removeOracle` is renamed as `index`, without the leading underscore.

This will in turn create a collision with the global `mapping(address => uint) index;`, which in this case can use a name that better describes what it is actually indexing.

**Comment by brendaloya** [comment]
done
