### ISSUE TITLE
Committing `build` folder is not needed

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/ADOMedianizer#4]
The repository currently contains a `build` folder that is not needed for compiling and migrating the project.

It is customary for Truffle projects to exclude such directory using a `.gitignore` directive.

This may seem innocuous, but let me argue that it could actually lead to a couple of unwanted situations:
- False positives when running tests and compiling with a different `solc` version, as the Truffle artifacts are already built.
- Privacy of the committer is harmed, as now we all know that he uses Windows and keeps his work-related documents in a folder called `company` :stuck_out_tongue:

**Comment by brendaloya** [comment]
yup, added /build to the .gitignore
