### ISSUE TITLE
Compiler version not fixed

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/ADOMedianizer#6]
https://github.com/tellor-io/ADOMedianizer/blob/77e38e08d6941e09c2247573e98711da6f986355/contracts/ADOMedianizer.sol#L47-L55

Only libraries, interfaces and inheritable contracts should use version ranges.

"Singleton" contracts that are expected to be instantiated and have their own address should fix a exact compiler version as future versions may handle certain language constructions in a way the developer did not foresee.

**Comment by brendaloya** [comment]
done
