### ISSUE TITLE
 Extra gas consumption 

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/ADOMedianizer#7]
https://github.com/tellor-io/ADOMedianizer/blob/77e38e08d6941e09c2247573e98711da6f986355/contracts/ADOMedianizer.sol#L32-L38

A state variable of non-memory array (`oracles.length`)  is used in the condition of the `for` loop. In this case, every iteration of loop consumes extra gas.

Holding the value of `oracles.length` in a local variable is more gas efficient for any case of `oracles.length > 1`, which we can assume is the case for a medianizer contract.

**Comment by brendaloya** [comment]
added local variable "num"
