### ISSUE TITLE
 Prefer external to public visibility level for `changeOwner`

### ISSUE THREAD

**Issue by aesedepece** [tellor-io/ADOMedianizer#9]
https://github.com/tellor-io/ADOMedianizer/blob/77e38e08d6941e09c2247573e98711da6f986355/contracts/ADOMedianizer.sol#L21-L23

`changeOwner` has `public` visibility modifier but is logically not called internally.

Changing visibility level to `external` increases code readability. Moreover, in many cases functions with `external` visibility modifier spend less gas comparing to functions with `public` visibility modifier.

**Comment by brendaloya** [comment]
Agreed.
